image: gitlab-registry.mpcdf.mpg.de/mpcdf/ci-module-image/intel_2024_0:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"


workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

tests:
  stage: test
  script:
    - module load git intel/2024.0 anaconda/3/2023.03
    - export CXX=icpx
    - export CC=icx
    - pip install -v .[tests]
    - export PATH=$PATH:/root/.local/bin
    - pytest -v tests/

pages-test:
  stage: test
  script:
    - module load git intel/2024.0 anaconda/3/2023.03
    - export CXX=icpx
    - export CC=icx
    - pip install .[docs]
    - export PATH=$PATH:/root/.local/bin
    - sphinx-build -W -b html doc/ doc-test/
  artifacts:
    paths:
      - doc-test
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'

pages:
  stage: deploy
  script:
    - module load git intel/2024.0 anaconda/3/2023.03
    - export CXX=icpx
    - export CC=icx
    - pip install .[docs]
    - export PATH=$PATH:/root/.local/bin
    - sphinx-build -b html doc/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

