#!/bin/sh

# I am not aware how arbitrary compiled binaries can be installed
# with python. So as a workaround ./test.cpp is compiled and installed
# by cmake and copied as part of the package data to the library dir.
# This wrapper here is then installed as a script by setuptools so that
# it is available from the (PYTHON-)PATH.

# find the test-app
TRIMEM_INST=$(python -c "import trimem; \
                         import pathlib; \
                         print(pathlib.Path(trimem.__file__).parent)")

if [[ -z $TRIMEM_INST ]]
then
  echo "Cannot find test-app."
  exit 1
fi

# pass on to test app
${TRIMEM_INST}/testd $@
